name: Aveds-test workflow

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r requirements.txt 

    - name: Test with flake8
      run: |
        python -m flake8
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Set up and push Backend Docker Buildx
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/aveds-test-backend:latest 
      - name: Set up and push Frontend Docker Buildx
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/aveds-test-frontend:latest 